export const INIT_CONNECTION_OBJ = 'INIT_CONNECTION_OBJ'
export const SET_CONNECTION_TEST = 'SET_CONNECTION_TEST'
export const SET_CONNECTION_INPUT_TABLES = 'SET_CONNECTION_INPUT_TABLES'
export const SET_CONNECTION_OUTPUT_TABLES = 'SET_CONNECTION_OUTPUT_TABLES'
